//LOCALHOST
### Get all Howard

Get https://cse341-wf7o.onrender.com/Howard

### Get all Fabian

Get https://cse341-wf7o.onrender.com/Fabian

//PRODUCTION
### Get all Howard

Get https://cse341-wf7o.onrender.com/Howard

### Get all Fabian

Get https://cse341-wf7o.onrender.com/Fabian